import { Location } from '../types/weather';

export const INDIA_LOCATIONS: Location[] = [
  {
    id: 'delhi',
    name: 'New Delhi',
    state: 'National Capital Territory',
    lat: 28.6139,
    lng: 77.2090,
    elevation: 216,
    climateZone: 'Semi-Arid',
    isHighRiskZone: true,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    lat: 19.0760,
    lng: 72.8777,
    elevation: 14,
    climateZone: 'Coastal Monsoon',
    isHighRiskZone: true,
  },
  {
    id: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    lat: 18.5204,
    lng: 73.8567,
    elevation: 560,
    climateZone: 'Semi-Arid',
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
    elevation: 920,
    climateZone: 'Tropical Wet',
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    lat: 17.3850,
    lng: 78.4867,
    elevation: 542,
    climateZone: 'Semi-Arid',
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5726,
    lng: 88.3639,
    elevation: 9,
    climateZone: 'Tropical Wet',
    isHighRiskZone: true,
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0827,
    lng: 80.2707,
    elevation: 6,
    climateZone: 'Coastal Monsoon',
    isHighRiskZone: true,
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0225,
    lng: 72.5714,
    elevation: 53,
    climateZone: 'Semi-Arid',
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    lat: 26.9124,
    lng: 75.7873,
    elevation: 431,
    climateZone: 'Semi-Arid',
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    lat: 26.8467,
    lng: 80.9462,
    elevation: 123,
    climateZone: 'Humid Subtropical',
  },
  {
    id: 'guwahati',
    name: 'Guwahati',
    state: 'Assam',
    lat: 26.1445,
    lng: 91.7362,
    elevation: 55,
    climateZone: 'Tropical Wet',
    isHighRiskZone: true,
  },
  {
    id: 'kochi',
    name: 'Kochi',
    state: 'Kerala',
    lat: 9.9312,
    lng: 76.2673,
    elevation: 2,
    climateZone: 'Coastal Monsoon',
  },
  {
    id: 'bhubaneswar',
    name: 'Bhubaneswar',
    state: 'Odisha',
    lat: 20.2961,
    lng: 85.8245,
    elevation: 45,
    climateZone: 'Coastal Monsoon',
    isHighRiskZone: true,
  },
  {
    id: 'srinagar',
    name: 'Srinagar',
    state: 'Jammu & Kashmir',
    lat: 34.0837,
    lng: 74.7973,
    elevation: 1585,
    climateZone: 'Mountainous',
    isHighRiskZone: true,
  },
  {
    id: 'bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    lat: 23.2599,
    lng: 77.4126,
    elevation: 527,
    climateZone: 'Humid Subtropical',
  },
  {
    id: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    lat: 22.7196,
    lng: 75.8577,
    elevation: 553,
    climateZone: 'Humid Subtropical',
  }
];

export const DEFAULT_LOCATION = INDIA_LOCATIONS[0]; // New Delhi
